### PR TITLE
[2851] Fix seeds.rb and add spec

### PR DESCRIPTION
**Pull request by timabell**
### Context

* Seeds file was broken
* CI didn't spot it

### Changes proposed in this pull request

* Fix the seeds
* Add a spec to exercise the seeds file

### Guidance to review

* `bundle exec rails db:reset`

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by timabell** [comment]
[[S] seeds broken](https://trello.com/c/t05S868U/2851-s-seeds-broken)

**Comment by timabell** [comment]
repro of interaction with modern languages cache:

```
rspec spec/requests/api/v3/providers/courses/index_spec.rb spec/seed_spec.rb
...
Failures:
  1) Seed seeds without error
     Failure/Error: load Rails.root.join("db/seeds.rb")
     ActiveRecord::RecordInvalid:
       Validation failed: Subjects Modern languages subjects must also have the modern_languages subject
     # ./db/seeds.rb:174:in `create_standard_provider_and_courses_for_cycle'
     # ./db/seeds.rb:265:in `<top (required)>'
     # ./spec/seed_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:61:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:60:in `block (2 levels) in <top (required)>'
```

**Comment by gpeng** [comment]
Can we rebase the 'linter' commit out before merging?

**Comment by timabell** [comment]
squashed linter commit, rebased on master

**Pull request merged**
