### PR TITLE
[489] Rubocop ToDo: Update enrichment model attributes to snake case

### PR DESCRIPTION
**Pull request by george-bit**
### Context

Clear up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2

### Changes proposed in this pull request

I've updated all of the camel case attributes across the enrichment models and associated specs to snake case to appease the linter.

### Guidance to review

All specs are still passing. But I may be missing an obious reason for these attribute being defined in Camel case.

If I am absent and this doesn't look right please feel free to close this PR.

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by darokel** [comment]
@george-bit I can see changes from some of the PRs here? eg the view component/super complaints

**Comment by george-bit** [comment]
[Clear rubocop_todo part 2](https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2)

**Review by defong — CHANGES_REQUESTED** [review]
Needs migrations, as the models interacts with `Jsonb` hence the Camel case as that is the actual object key being saved into the database

**Comment by stellenberger** [comment]
Putting this on the backburner until the migration from Publish to TTAPI is completed

**Pull request closed without merging**
