### PR TITLE
[711] Smoke test for healthcheck and courses index routes

### PR DESCRIPTION
**Pull request by AbigailMcP**
### Context

https://trello.com/c/tcSBRSoL/711-m-healthcheck-smoke-test
https://trello.com/c/2EUGHq7k/713-m-courses-endpoint-smoke-tests

### Changes proposed in this pull request

- Smoke test to check V1 /healthcheck endpoint returns HTTP status of 200, json and expected shape
- Smoke test to check V1 /courses endpoint returns HTTP status of 200

### Guidance to review

As per the instructions in https://github.com/DFE-Digital/teacher-training-api/pull/1725

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[[M] Courses endpoint smoke tests](https://trello.com/c/2EUGHq7k/713-m-courses-endpoint-smoke-tests)

**Comment by AbigailMcP** [comment]
[[M] Healthcheck smoke test](https://trello.com/c/tcSBRSoL/711-m-healthcheck-smoke-test)

**Comment by felixtheflex** [comment]
[Investigate load-balancing and redundancy](https://trello.com/c/obXjan4G/854-investigate-load-balancing-and-redundancy)

**Review by defong — CHANGES_REQUESTED** [review]
A few minor but annoying bits

**Comment by AbigailMcP** [comment]
@defong thanks! changed the URL and now checking that at least one record is returned in courses data. not sure what you mean by `meta.count != 0` though?

**Comment by defong** [comment]
> @defong thanks! changed the URL and now checking that at least one record is returned in courses data. not sure what you mean by `meta.count != 0` though?

Sorry I meant greater than 1 

image

Its the total course count that is available

**Comment by AbigailMcP** [comment]
@defong - as discussed, looks like `meta` in only on qa at the moment. Should I add the test in anticipation make new PR adding the extra assertion later?

**Comment by AbigailMcP** [comment]
[[M] Courses endpoint smoke tests](https://trello.com/c/2EUGHq7k/713-m-courses-endpoint-smoke-tests)

**Review by defong — APPROVED** [review]

**Pull request merged**
