### PR TITLE
3458 Rename create to publish throughout the notifications code

### PR DESCRIPTION
**Pull request by gpeng**
### Context

We have launched the notification feature. This PR tidies up some inconsistencies that we introduced as we developed the feature.

### Changes proposed in this pull request

* Rename `UserNotification#course_create` to `course_publish` throughout. The email is sent when a course is published not created
* Rename `Courses::PublishService` to `NotificationService::CoursePublished`. The service only sends a notification currently so this naming is more consistent with its function.
* Rename `Courses::UpdateNotificationService` to `NotificationService::CourseUpdated` to make it consistent with above.
* Refactor the services to make them consistent with the pattern we've introduced in Publish. Use the `ServicePattern` module.
* Refactor some specs to reduce the number of DB objects required to run them.
* Remove some code that was used in earlier implementations of this feature but is no longer required (`UserNotification.find_or_initialize`)

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Comment by gpeng** [comment]
[[M] Rename `create` to `publish` throughout the notifications code](https://trello.com/c/zxFwsm2N/3458-m-rename-create-to-publish-throughout-the-notifications-code)

**Comment by karthikdfe** [comment]
@gpeng @defong Did we test this on QA?

**Comment by gpeng** [comment]
@karthikdfe Not yet. I'm going to merge and do that this morning. We can 'finesse' it on there before I deploy :)

**Comment by karthikdfe** [comment]
@gpeng any reason why we not testing this on QA before merging into master?

**Comment by gpeng** [comment]
@karthikdfe Only that it's a faff to deploy the branch and then have to deploy master and we don't have review apps for this repo. I don't envisage there being a massive problem, I just need to see how the azure template works with the environment variables I can deploy it as a branch if you prefer. 🤷

**Comment by gpeng** [comment]
The branch has been tested on QA and the pipeline changes are working.

**Pull request merged**
