### PR TITLE
[xxx] Run rubocop in CI

### PR DESCRIPTION
**Pull request by gpeng**
This should need https://github.com/DFE-Digital/teacher-training-api/pull/1982 to be merged before it will pass CI. 

### Context

It wasn't running. It is now.

### Changes proposed in this pull request

* run it

### Guidance to review

* Look at the GitHub actions log and see if it ran. https://github.com/DFE-Digital/teacher-training-api/runs/2842537644?check_suite_focus=true (spoilers: it did and failed as we need the PR up there ^ merged)
* In the other apps we specify specific directories that should be linted. I think this belongs in the rubocop config rather than in the build command so I've not done that here. 

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Comment by gpeng** [comment]
[Remove rubocop-govuk](https://trello.com/c/GmVrACXA/2011-remove-rubocop-govuk)

**Review by defong — CHANGES_REQUESTED** [review]
Can we move this right at the top, as it literal the fastest no ops.

**Review by vigneshmsft — APPROVED** [review]
nice...didn't realise it wasn't being ran.

**Comment by gpeng** [comment]
> Can we move this right at the top, as it literal the fastest no ops.

We can only move it a couple of steps up because we need the docker image to have been built. I do wonder if we should only deploy the review app after the tests have passed though. @vigneshmsft what do you think?

So we'd have:

* build the things
* lint
* test
* deploy (review app or to prod)
* alert

**Review by defong — APPROVED** [review]
We need to revisit devops/CI as this is kinda useless.

Other then failing it don't inform us what failed, self failures.

image

**Pull request merged**
