### PR TITLE
2268 add urn ukprn to public api

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
- URN and UKPRN

### Changes proposed in this pull request
- Add URN and UKPRN to public API and docs

### Guidance to review
`/api-reference.html#recruitment_cycles-year-providers-provider_code-get-responses-examples`

### Checklist
Screenshot 2021-07-15 at 12 47 16
Screenshot 2021-07-15 at 12 47 13

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by dankmitchell** [comment]
[Add URN and UKPRN to Public API](https://trello.com/c/bFGR4s7A/2268-add-urn-and-ukprn-to-public-api)

**Comment by defong** [comment]
Broken tests?

https://github.com/DFE-Digital/teacher-training-api/pull/2059/checks?check_run_id=3077493796#step:12:522

**Comment by dankmitchell** [comment]
> Broken tests?
> 
> https://github.com/DFE-Digital/teacher-training-api/pull/2059/checks?check_run_id=3077493796#step:12:522

All fixed

**Review by defong — CHANGES_REQUESTED** [review]
https://trello.com/c/cHdOGMkz/3930-s-add-validation-to-urn-location

5 or 6 or just 6?

**Review by defong — APPROVED** [review]

**Pull request merged**
