### PR TITLE
[2803] Fix subjects namepace

### PR DESCRIPTION
**Pull request by defong**
### Context
Introduce module `Subjects` for those subject related services

### Changes proposed in this pull request
Restructured code and folder structure to match module

### Guidance to review
:confounded: 

needed to do
```
Subjects::* vs ::*
ie
Subjects::PrimarySubject vs ::PrimarySubject
```

Subject classes are STI

probably wrong

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Comment by defong** [comment]
[Some subjects has subject knowledge enhancement (SKE) course associated with it](https://trello.com/c/SK4930X3/2803-some-subjects-has-subject-knowledge-enhancement-ske-course-associated-with-it)

**Comment by misaka** [comment]
@defong Should this still be draft? Looks ok to me.

**Comment by dankmitchell** [comment]
@defong should we fix the actual subjects whilst we;re here i.e.

```
module Subject
  class Primary < Subject
  end
end
```

instead of 

```
  class PrimarySubject < Subject
  end
```

**Comment by defong** [comment]
@danmitchell I think I saw floppy ears going that STI hole...

**Comment by dankmitchell** [comment]
@defong 🐇

**Comment by dankmitchell** [comment]
Ship this. Subject modules can come later

**Pull request merged**
